language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

install:
  - make install-test-deps
  - travis_retry composer update --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
