language: php

php:
  - 7.0

sudo: false

matrix:
  fast_finish: true

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - make install-test-deps
  - travis_retry composer update --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
