language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

install:
  - make install-test-deps
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - travis_retry composer update --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
